name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v4

      - name: Set up latest Docker
        uses: docker/setup-docker-action@v5
        with:
          version: latest

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Run tests in Docker
        run: PYTHON_VERSION=${{ matrix.python }} docker compose run --rm --build python-clamd-test
